export const QUERY_SHOP_INFO = "query-shop-info"
export const QUERY_RESERVATION_ARR = "query-reservation-arr"
export const QUERY_POST_ARR = "query-post-arr"
export const LIST_RESERVATION_QUERY = "get-list-reservation"
export const VIEW_RESERVATION_QUERY = "get-view-reservation"
export const QUERY_LIST_SHOP_NAIL_ARTIST = "get-list-shop-nail-artist"
export const QUERY_MAINPAGE_QUERY = "get-main-page-data"
